apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-grpc-server
  template:
    metadata:
      labels:
        app: go-grpc-server
    spec:
      containers:
      - name: go-grpc-server
        image: go-grpc-server:latest  
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-grpc-server
spec:
  selector:
    app: go-grpc-server
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
