# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\"\"\n\x12\x43reateUserResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"N\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\"\"\n\x12UpdateUserResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x12\x44\x65leteUserResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"8\n\x13GetAllUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse2\xb9\x02\n\x0bUserService\x12\x30\n\x07GetUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12?\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12?\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponse\x12\x35\n\x0bGetAllUsers\x12\x0b.user.Empty\x1a\x19.user.GetAllUsersResponseB\x0fZ\rgrpc_go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\rgrpc_go/proto'
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=45
  _globals['_USERRESPONSE']._serialized_start=47
  _globals['_USERRESPONSE']._serialized_end=120
  _globals['_CREATEUSERREQUEST']._serialized_start=122
  _globals['_CREATEUSERREQUEST']._serialized_end=188
  _globals['_CREATEUSERRESPONSE']._serialized_start=190
  _globals['_CREATEUSERRESPONSE']._serialized_end=224
  _globals['_UPDATEUSERREQUEST']._serialized_start=226
  _globals['_UPDATEUSERREQUEST']._serialized_end=304
  _globals['_UPDATEUSERRESPONSE']._serialized_start=306
  _globals['_UPDATEUSERRESPONSE']._serialized_end=340
  _globals['_DELETEUSERREQUEST']._serialized_start=342
  _globals['_DELETEUSERREQUEST']._serialized_end=373
  _globals['_DELETEUSERRESPONSE']._serialized_start=375
  _globals['_DELETEUSERRESPONSE']._serialized_end=409
  _globals['_EMPTY']._serialized_start=411
  _globals['_EMPTY']._serialized_end=418
  _globals['_GETALLUSERSRESPONSE']._serialized_start=420
  _globals['_GETALLUSERSRESPONSE']._serialized_end=476
  _globals['_USERSERVICE']._serialized_start=479
  _globals['_USERSERVICE']._serialized_end=792
# @@protoc_insertion_point(module_scope)
